import React, { useEffect, useState } from 'react';
import { Plus, X } from 'lucide-react';
import { createRunSheetItem, deleteRunSheetItem, listRunSheetItemsByProductionDay, updateRunSheetItem } from '../runSheetService';
import RunSheetItem from './RunSheetItem';
import RunSheetTimeInput from './RunSheetTimeInput';

const emptyItem = { time: '', title: '', owner: '', location: '', note: '' };

const RunSheetEditor = ({ productionDay, canManage, userId, onClose }) => {
    const [items, setItems] = useState([]); const [draft, setDraft] = useState(emptyItem); const [editing, setEditing] = useState(null);
    const load = async () => setItems(await listRunSheetItemsByProductionDay(productionDay.id));
    useEffect(() => { load().catch(() => setItems([])); }, [productionDay.id]);
    const save = async (event) => { event.preventDefault(); const payload = { ...draft, productionDayId: productionDay.id, order: editing?.order ?? items.length }; if (editing) await updateRunSheetItem(editing.id, payload, userId); else await createRunSheetItem(payload, userId); setDraft(emptyItem); setEditing(null); await load(); };
    const remove = async (id) => { if (window.confirm('Xóa mục lịch trình này?')) { await deleteRunSheetItem(id); await load(); } };
    const move = async (item, direction) => { const index = items.findIndex((entry) => entry.id === item.id); const target = items[index + direction]; if (!target) return; await Promise.all([updateRunSheetItem(item.id, { ...item, order: target.order }, userId), updateRunSheetItem(target.id, { ...target, order: item.order }, userId)]); await load(); };
    return <div className="fixed inset-0 z-[60] flex items-end bg-black/70 md:items-center md:justify-center"><div className="max-h-[92dvh] w-full max-w-2xl overflow-y-auto rounded-t-2xl border border-vps-gray/20 bg-[#151515] p-5 md:rounded-2xl"><div className="flex items-center justify-between"><div><p className="text-sm text-vps-gold/70">Run sheet</p><h2 className="text-lg font-semibold text-vps-ivory">{productionDay.title}</h2></div><button onClick={onClose} className="rounded-lg bg-[#222] p-2 text-vps-ivory"><X className="h-5 w-5" /></button></div>{canManage ? <form onSubmit={save} className="mt-5 rounded-xl border border-vps-gray/20 bg-[#111] p-3"><div className="grid gap-3 sm:grid-cols-2"><RunSheetTimeInput value={draft.time} onChange={(time) => setDraft({ ...draft, time })} /><input required placeholder="Hoạt động" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} className="rounded-lg border border-vps-gray/20 bg-[#181818] px-3 py-2 text-sm text-vps-ivory outline-none focus:border-vps-gold" /><input placeholder="Người phụ trách" value={draft.owner} onChange={(event) => setDraft({ ...draft, owner: event.target.value })} className="rounded-lg border border-vps-gray/20 bg-[#181818] px-3 py-2 text-sm text-vps-ivory outline-none focus:border-vps-gold" /><input placeholder="Địa điểm" value={draft.location} onChange={(event) => setDraft({ ...draft, location: event.target.value })} className="rounded-lg border border-vps-gray/20 bg-[#181818] px-3 py-2 text-sm text-vps-ivory outline-none focus:border-vps-gold" /></div><textarea rows="2" placeholder="Ghi chú" value={draft.note} onChange={(event) => setDraft({ ...draft, note: event.target.value })} className="mt-3 w-full rounded-lg border border-vps-gray/20 bg-[#181818] px-3 py-2 text-sm text-vps-ivory outline-none focus:border-vps-gold" /><div className="mt-3 flex justify-end gap-2">{editing ? <button type="button" onClick={() => { setEditing(null); setDraft(emptyItem); }} className="rounded-lg border border-vps-gray/20 px-3 py-2 text-sm text-vps-ivory">Hủy sửa</button> : null}<button className="inline-flex items-center gap-2 rounded-lg bg-vps-gold px-3 py-2 text-sm font-semibold text-vps-black"><Plus className="h-4 w-4" />{editing ? 'Lưu mục' : 'Thêm mục'}</button></div></form> : null}<div className="mt-4 space-y-2">{items.length ? items.map((item) => <RunSheetItem key={item.id} item={item} canManage={canManage} onDelete={remove} onMove={move} onEdit={(entry) => { setEditing(entry); setDraft(entry); }} />) : <p className="rounded-xl border border-dashed border-vps-gray/30 p-4 text-sm text-vps-ivory/60">Chưa có lịch trình chi tiết.</p>}</div></div></div>;
};

export default RunSheetEditor;